name: Generar artículo semanal

on:
  schedule:
    - cron: '0 8 * * 1'  # Cada lunes a las 8:00 AM UTC
  workflow_dispatch:     # Para probar manualmente

jobs:
  generate-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: |
          pip install requests

      - name: Generate article with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Llamar a Gemini para obtener título y contenido
          RESPONSE=$(curl -s -X POST \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{
              "contents": [{
                "parts": [{
                  "text": "Sugiere un tema técnico sobre Docker, DevOps o Linux en español. Solo el título."
                }]
              }],
              "generationConfig": {
                "temperature": 0.7,
                "maxOutputTokens": 100
              }
            }')

          TITLE=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['candidates'][0]['content']['parts'][0]['text'].strip().replace('#', ''))")

          # Verificar duplicados
          if [ -f "_data/topics-used.json" ]; then
            if grep -q "$TITLE" "_data/topics-used.json"; then
              echo "Tema duplicado. Saliendo."
              exit 0
            fi
          fi

          # Generar contenido completo
          FULL_RESPONSE=$(curl -s -X POST \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{
              "contents": [{
                "parts": [{
                  "text": "Escribe un artículo técnico en español sobre: '"$TITLE"'. Incluye requisitos, código, errores comunes, solución. Que esto sea algo completo y muy informativo. Usa Warnings, notes, info. Agrega tambien algo de buenas practicas. Formato Markdown."
                }]
              }],
              "generationConfig": {
                "temperature": 0.7,
                "maxOutputTokens": 1500
              }
            }')

          CONTENT=$(echo "$FULL_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['candidates'][0]['content']['parts'][0]['text'].strip())")

          # Crear archivo con front matter
          DATE=$(date +"%Y-%m-%d")
          FILENAME="_posts/${DATE}-articulo-tecnico.md"
          echo "---" > "$FILENAME"
          echo "title: $TITLE" >> "$FILENAME"
          echo "date: $(date +"%Y-%m-%d %H:%M:%S")" >> "$FILENAME"
          echo "---" >> "$FILENAME"
          echo "" >> "$FILENAME"
          echo "$CONTENT" >> "$FILENAME"

          # Actualizar topics-used.json
          jq --arg t "$TITLE" --arg d "$DATE" \
            '. += [{"title": $t, "date": $d}]' \
            _data/topics-used.json > tmp.$$.json && mv tmp.$$.json _data/topics-used.json || echo '[{"title": "'"$TITLE"'", "date": "'"$DATE"'"}]' > _data/topics-used.json
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOWS }}
          title: "📰 Artículo Semanal"
          body: "Generado automáticamente"
          branch: "weekly-PR"
          base: main
          assignees: Hector295
          labels: automated